### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.hive.jdbc.HiveDriver

### ISSUE THREAD

**Issue by Myarnzero** [dstreev/hms-mirror#38]
There is a problem when I execute `hms-mirror -db tpcds_text_2 -e`.

> 
[root@host3 aux_libs]# hms-mirror -db tpcds_text_2 -e
APP_DIR: /usr/local/hms-mirror/bin
Running Host instance
Application JAVA_OPTS=-Xms2048m -Xmx4096m -XX:+UseG1GC
PRG_ARGS= "-db" "tpcds_text_2" "-e"
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
Using Config: /root/.hms-mirror/cfg/default.yaml
----------------------------------------
.... Accept/Acknowledge to continue ....
----------------------------------------
I have made backups of both the 'Hive Metastore' in the LEFT and RIGHT clusters (TRUE to proceed): true
I have taken 'Filesystem' Snapshots/Backups of the target 'Hive Databases' on the LEFT and RIGHT clusters (TRUE to proceed): true
'Filesystem' TRASH has been configured on my system (TRUE to proceed): true
java.lang.ClassNotFoundException: org.apache.hive.jdbc.HiveDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:822)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.cloudera.utils.hadoop.hms.util.DriverUtils.getDriver(DriverUtils.java:44)
        at com.cloudera.utils.hadoop.hms.mirror.ConnectionPools.initDrivers(ConnectionPools.java:59)
        at com.cloudera.utils.hadoop.hms.mirror.ConnectionPools.init(ConnectionPools.java:49)
        at com.cloudera.utils.hadoop.hms.Mirror.init(Mirror.java:561)
        at com.cloudera.utils.hadoop.hms.Mirror.main(Mirror.java:1073)
HMS-Mirror v.1.4.0.2-SNAPSHOT                            Data Strategy: SCHEMA_ONLY*

DB/TBL  Total:(1/0)
===================================================================================

===================================================================================
TBLS (Started/Completed/Errors)->(0/0/0)           Elapse Time: 0secs

Run Mode                 : EXECUTE
Config file             : /root/.hms-mirror/cfg/default.yaml
HMS-Mirror v.1.4.0.2-SNAPSHOT                            Data Strategy: SCHEMA_ONLY

DB/TBL  Total:(1/0)
===================================================================================

===================================================================================
TBLS (Started/Completed/Errors)->(0/0/0)           Elapse Time: 0secs

Run Mode                 : EXECUTE
Config file             : /root/.hms-mirror/cfg/default.yaml

Databases(<db>):
tpcds_text_2

Report file              : /root/.hms-mirror/reports/2021-12-24_15-54-44/<db>_hms-mirror.md|html
LEFT Execute file        : /root/.hms-mirror/reports/2021-12-24_15-54-44/<db>_LEFT_execute.sql
RIGHT Execute file       : /root/.hms-mirror/reports/2021-12-24_15-54-44/<db>_RIGHT_execute.sql
LEFT Action file         : /root/.hms-mirror/reports/2021-12-24_15-54-44/<db>_LEFT_action.sql
RIGHT Action file        : /root/.hms-mirror/reports/2021-12-24_15-54-44/<db>_RIGHT_action.sql
> 
Configuration：
> 
transfer:
  concurrency: 10
  transferPrefix: "transfer_"
  exportBaseDirPrefix: "/apps/hive/warehouse/export_"
clusters:
  LEFT:
    legacyHive: true
    hcfsNamespace: "hdfs://192.******/tmp/hivemove/"
    hiveServer2:
      uri: "jdbc:hive2://192.******:10000"
      connectionProperties:
        user: "hive"
        password: " "
      jarFile: "/usr/hdp/current/hive-server2/jdbc/hive-jdbc-1.2.1000.2.6.5.0-292-standalone.jar"
  RIGHT:
    legacyHive: false
    hcfsNamespace: "hdfs://192.*******/tmp/hivemove/"
    hiveServer2:
      uri: "jdbc:hive2://192.*******:10000/;principal=hive/host3.localdomain@HADOOP.COM"
      connectionProperties:
        user: "hive"
        password: " "
     # jarFile: "/opt/cloudera/parcels/CDH/jars/hive-jdbc-3.1.3000.7.1.5.0-257-standalone.jar"
    partitionDiscovery:
      auto: true
      initMSCK: true

>

**Comment by dstreev** [comment]
The jar file for the "RIGHT" cluster needs to be in $HOME/.hms-mirror/aux_libs since it's commented out in the config.

**Comment by Myarnzero** [comment]
> The jar file for the "RIGHT" cluster needs to be in $HOME/.hms-mirror/aux_libs since it's commented out in the config.

Yes, I did. 
If this is not done, another error will occur.

[root@host3 ~]# cd .hms-mirror/aux_libs/
[root@host3 aux_libs]# ls
hive-jdbc-3.1.3000.7.1.5.0-257-standalone.jar

**Comment by dstreev** [comment]
The LEFT clusters JDBC driver you're referencing in the config is on the host your running hms-mirror from?  Seems like you're referencing an HDP installation and I assume you're running hms-mirror on a CDP host, so this file wouldn't be present.

**Comment by Myarnzero** [comment]
You are right. I copied the jdbc driver of the LEFT cluster to the RIGHT cluster. This problem has been solved.

**Comment by Myarnzero** [comment]
Thanks ,you are right. I copied the jdbc driver of the LEFT cluster to the RIGHT cluster. This problem has been solved.
