### ISSUE TITLE
HiveAccessControlException Permission denied: user [hms] does not have [ALL] privilege

### ISSUE THREAD

**Issue by Myarnzero** [dstreev/hms-mirror#42]
Hi Dstreev，

I encountered the problems mentioned in the document:

> FAILED: HiveAccessControlException Permission denied: user [hms] does not have [ALL] privilege on [ hdfs://hdp1.localdomain:8020/extwarehouse/tpcd/2/web_sales ]

I have tried the following methods:
Use Ranger to grant full permissions to HDFS and hive to user "hms".
Set the ACL of HDFS for user "hms".
Add user "hms" to 'dfs. permissions. superusergroup' in 'hdfs-site.xml'
But it didn't work.

And I can't run the following command successfully. (My Ambari and Namenode are no longer on the same host. I don't know if it's because of this.)

> sudo ./ configs. py --host=hdp4 --port=8080 -u admin -p admin -n hdp1. localdomain -c hdfs-site -a set -k dfs. permissions. superusergroup -v hms

Did I miss anything？Or made a mistake?

Thank you for your help.

**Comment by dstreev** [comment]
What part of the process is complaining about this?  Is this on the LEFT of RIGHT cluster?  What does your config look like?  Do you get the same error when you run the command in hive cli?  Is the RIGHT cluster LINKED to the LEFT?

**Comment by Myarnzero** [comment]
When I execute  ‘hms-mirror -db tpcds_text_2 -e’ on the RIGHT cluster, I didn't succeed. Check the log, which records the error.

Moreover, the log records the hive table creation statements obtained from the LEFT cluster. When I execute these table creation statements in hive cli, I also report this error because the address in the ‘LOCATION’ belongs to the LEFT cluster.

And I execute this command：

> sudo ./ configs. py --host=hdp4 --port=8080 -u admin -p admin -n hdp1. localdomain -c hdfs-site -a set -k dfs. permissions. superusergroup -v hms

ERROR：Exception: Problem with accessing api. Reason: HTTP Error 404: Not Found

Configuration：
transfer:
concurrency: 10
transferPrefix: "transfer_"
exportBaseDirPrefix: "/apps/hive/warehouse/export_"
clusters:
LEFT:
legacyHive: true
hcfsNamespace: "hdfs://hdp1/tmp/hivemove/"
hiveServer2:
uri: "jdbc:hive2://192.*****:10000"
connectionProperties:
user: "hive"
password: " "
jarFile: "/usr/hdp/current/hive-server2/jdbc/hive-jdbc-1.2.1000.2.6.5.0-292-standalone.jar"
RIGHT:
legacyHive: false
hcfsNamespace: "hdfs://host1/tmp/hivemove/"
hiveServer2:
uri: "jdbc:hive2://192.****:10000/;principal=hive/host3.localdomain@HADOOP.COM"
connectionProperties:
user: "hive"
password: " "
# jarFile: ""
partitionDiscovery:
auto: true
initMSCK: true

thanks

**Comment by dstreev** [comment]
A few things to do:
1. The RIGHT cluster `jarFile` should be 'commented' out, not an empty string.
2. The hive standalone jar for the RIGHT cluster should be in $HOME/.hms-mirror/aux_libs so it get picked up by the classpath.
3. You need a kerberos ticket before running `hms-mirror`
4. The jarFile for the LEFT cluster seems to be in a path that is specific to an HDP environment, even though `hms-mirror` is running on a CDP edge node.  Please verify.  DO NOT put this jarFile in the 'aux_libs' dir mentioned above.
5. The namespaces are too long and have dir locations.  So the application is NOT able to match the LEFT namespace to the elements in the location and replace them with the RIGHT namespace.  These should ONLY be the namespace, not a path.

**Comment by Myarnzero** [comment]
Thanks. I ran it successfully.
I mistakenly think that `hcfsnamespace `is a URL. In fact, it is more like a variable.
